//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAHub_ASPWebforms
{


    public partial class GrantOfficerGrants
    {

        /// <summary>
        /// USERCONTROL_GrantDDisplay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::JAHub_ASPWebforms.Grant_Controls.USERCONTROL_GrantDDisplay USERCONTROL_GrantDDisplay1;
    }
}
